---
title: "1204.3-mtdna"
output: html_document
date: "2025-01-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

Have some mtDNA from WJC. Checking it out.

```{r}
library(tidyverse)
```

aligned with mafft

in outputs/1204/mtdna
(base) ➜  mtdna git:(main) ✗ iqtree2 -nt AUTO -s coi-wjc.afasta -T AUTO -st DNA -m MFP -bb 10000 --redo 

now-no og

 mafft coi-wjc-noog.fasta > coi-wjc-noog.afasta
 
iqtree2 -nt AUTO -s coi-wjc-noog.afasta -T AUTO -st DNA -m MFP -bb 10000 --redo 

```{r}
tree<-read.tree("outputs/1204/mtdna/coi-wjc-noog.afasta.contree")
t2<-midpoint.root(tree)
t3<-as.polytomy(t2, feature='node.label', fun=function(x) as.numeric(x) < 75)

t<-t3

t<-ggtree(t)

t$data$Bootstrap<-as.numeric(t$data$label)

d <- t$data
d <- d[!d$isTip,]
d$label <- as.numeric(d$label)
d <- d[d$label >= 90,]

e <- t$data
e <- e[!e$isTip,]
e$label <- as.numeric(e$label)
e <- e[e$label < 90,]
e <- e[e$label >= 75,]
```



```{r}
m2<-read_csv("meta/combined-mtdna.csv")
u<-t %<+% m2 + #bind_rows(m58, rm) +
  geom_point(data=e,  fill="gray50", cex=2, alpha=1, pch=21) +
  geom_point(data=d,  fill="black", cex=2, alpha=1, pch=21) +
  geom_tiplab(aes(label=paste0(label," ",Region), x=x+0.001), align = FALSE, size=2) +
  #geom_text(data=t$data %>% filter(isTip==TRUE) %>% filter(label %in% Run), aes(label=label, x=x+0.01), size=3) +
  guides(fill = guide_legend(override.aes = list(pch = 22))) +
  xlim(0,.07) +
  scale_fill_viridis_d(option="H") +
  theme(legend.position = "none") +
  geom_treescale()

u
ggsave("outputs/1204/mtdna-coi-phylo.pdf", width=6.5, height=8)
```
  