---
title: "1309-pilbara-filtered"
output: html_document
date: "2025-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


```{r}
library(tidyverse)
library(raster)
library(ozmaps)
library(ggrepel)
library(ggtree)
library(tanggle)
library(phangorn)
library(viridis)
library(ggpubr)
library(grid)
library(ape)
library(RColorBrewer)
library(pcadapt)
library(ggpubr)
```

Drop the two odd fish and filter SNPS

```{r}
meta<-read_csv("meta/aus-wgs-61.csv") %>% filter(Run !="WAF011639") %>% filter(Run != "Broome01")

meta %>% dplyr::select(Run) %>% write_tsv("outputs/1309/samples-59.txt", col_names = FALSE)

meta$Locality<-factor(meta$Locality, levels=c("DeGrey River","Broome","Fitzroy River WA","Daly River","Darwin Harbour","Roper River","Tully Inlet","Fly River","Hinchinbrook Channel", "Fitzroy River QLD"))
```


```{sh, eval=FALSE}
bcftools view -S outputs/1309/samples-59.txt outputs/1308/renamed-05.vcf.gz > outputs/1309/renamed-05.vcf


bcftools +fill-tags outputs/1309/renamed-05.vcf  -- -t MAF,F_MISSING | bcftools view -i 'F_MISSING < 0.05' | bcftools view -i 'INFO/MAF > 0.05' |  bcftools +prune -m 0.20 -w 50kb --nsites-per-win 1 --nsites-per-win-mode maxAF  > outputs/1309/pruned-05.vcf

bcftools +fill-tags outputs/1309/renamed-05.vcf  -- -t MAF,F_MISSING | bcftools view -i 'F_MISSING < 0.05' | bcftools view -i 'INFO/MAF > 0.05' |  bcftools +prune -m 0.20 -w 50kb --nsites-per-win 1 --nsites-per-win-mode rand  > outputs/1309/pruned-05-rand.vcf
```


## Copy from here

```{r}
path_to_file <- "outputs/1309/pruned-05.vcf"

filename <- read.pcadapt(path_to_file, type = "vcf")
```



_1_ choose a K   

```{r}
x <- pcadapt(input = filename, K = 20) 
```

```{r}
var<-round(x$singular.values^2*100,2)
var
```

```{r}
#plot(x, option = "screeplot")
panela<-plot(x, option = "screeplot", K = 10) + ggtitle("A") +
  theme(plot.title = element_text(size=14, face="bold")) +
  theme(panel.grid = element_blank(), panel.background = element_blank()) +
  scale_x_continuous(breaks=seq(1,10,1), labels=seq(1,10,1)) +
  ylab("Proption of Explained Variance\n") +
  xlab("\nPrincipal Component") +
  theme(axis.title=element_text(size=12))
panela
```

```{r}
m<-meta
```

```{r}
plot(x, option = "scores", pop = factor(m$Region, levels=c("Western Australia","Northern Territory","Papua New Guinea","Queensland")))
 
```




Get scree plot and PCA    
```{r}
pcadata<-x$scores[,1:5] %>% as_tibble()
pcadata<-pcadata %>% bind_cols(m)

```

```{r}
ggplot(pcadata) +
  geom_point(aes(x=V1, y=V2, shape=Lineage, fill=Region), alpha=0.95) +
  #geom_text_repel(data=pcadata %>% filter(Region %in% c("Cambodia")), aes(x=V1, y=V2,label=Run)) +
  scale_shape_manual(values=c(21,23,23,24,22)) + 
  scale_fill_viridis_d(option="C") +
  guides(fill = guide_legend(override.aes = list(pch = 22))) +
  theme_bw() +
  theme(legend.position = "none") +
  theme(panel.grid = element_blank()) +
  xlab("PC 1") +
  ylab("PC 2") 

ggplot(pcadata) +
  geom_point(aes(x=V1, y=V3, shape=Lineage, fill=Region), alpha=0.95) +
 # geom_text_repel(data=pcadata %>% filter(Region %in% c("Queensland")), aes(x=V1, y=V4,label=Run)) +
  scale_shape_manual(values=c(21,23,23,24,22)) + 
  scale_fill_viridis_d(option="C") +
  guides(fill = guide_legend(override.aes = list(pch = 22))) +
  theme_bw() +
  theme(legend.position = "none") +
  theme(panel.grid = element_blank()) +
  xlab("PC 1") +
  ylab("PC 3") 
```


```{r}
labels12<-pcadata %>% dplyr::select(Locality,V1, V2) %>% group_by(Locality) %>% summarize(x=mean(V1), y=mean(V2)) 


pcb<-ggplot(pcadata) +
  geom_point(aes(x=V1, y=V2, shape=Lineage, fill=Locality), alpha=0.95) +
  geom_label_repel(data=labels12, aes(x=x, y=y, label=Locality, fill=Locality), alpha=0.8, size=3) +
  scale_shape_manual(values=c(21,23,23,24,22)) + 
  scale_fill_viridis_d(option="H") +
  guides(fill = guide_legend(override.aes = list(pch = 22))) +
  theme_bw() +
  theme(legend.position = "none") +
  theme(panel.grid = element_blank()) +
  xlab("PC 1") +
  ylab("PC 2") +
  ggtitle("B") +
  theme(plot.title = element_text(size=14, face="bold")) 

labels13<-pcadata %>% dplyr::select(Locality,V1, V3) %>% group_by(Locality) %>% summarize(x=mean(V1), y=mean(V3)) 

pcc<-ggplot(pcadata) +
  geom_point(aes(x=V1, y=V3, shape=Lineage, fill=Locality), alpha=0.9) +
  geom_label_repel(data=labels13, aes(x=x, y=y, label=Locality, fill=Locality), alpha=0.8, size=3) +
  scale_shape_manual(values=c(21,23,23,24,22)) + 
  scale_fill_viridis_d(option="H") +
  guides(fill = guide_legend(override.aes = list(pch = 22))) +
  theme_bw() +
  theme(panel.grid = element_blank()) +
  theme(legend.position = "none") +

  xlab("PC 1") +
  ylab("PC 3") +
  ggtitle("C") +
  theme(plot.title = element_text(size=14, face="bold")) 

labels14<-pcadata %>% dplyr::select(Locality,V1, V4) %>% group_by(Locality) %>% summarize(x=mean(V1), y=mean(V4)) 

pcd<-ggplot(pcadata) +
  geom_point(aes(x=V1, y=V4, shape=Lineage, fill=Locality), alpha=0.9) +
  geom_label_repel(data=labels14, aes(x=x, y=y, label=Locality, fill=Locality), alpha=0.8, size=3) +
  scale_shape_manual(values=c(21,23,23,24,22)) + 
  scale_fill_viridis_d(option="H") +
  guides(fill = guide_legend(override.aes = list(pch = 22))) +
  theme_bw() +
  theme(panel.grid = element_blank()) +
  xlab("PC 1") +
  ylab("PC 4") +
  ggtitle("C") +
  theme(plot.title = element_text(size=14, face="bold")) 
```

```{r}
blank <- grid.rect(gp=gpar(col="white"))
```



```{r}
a<-ggplotGrob(ggarrange(panela, pcb, blank, ncol=3, widths=c(1,1.2,.5)))
bc<-ggplotGrob(ggarrange(pcc, pcd, ncol=2, widths=c(1,1.4)))
ggarrange(a,bc, ncol=1, heights=c(1,1))

ggsave("outputs/1309/called-snp-pcas.pdf", width=12, height=10)
```





```{r}
Region<-pcadata %>% dplyr::select(Region,V1, V2) %>% group_by(Region) %>% summarize(x=mean(V1), y=mean(V2)) 
Locality<-pcadata %>% dplyr::select(Locality,V1, V2) %>% group_by(Locality) %>% summarize(x=mean(V1), y=mean(V2)) 
pvar <- x$singular.values^2

ggplot(pcadata) +
  geom_point(aes(x=V1, y=V2, shape=Lineage, fill=Locality), alpha=0.8, size=4) +
  geom_text_repel(data=Region, aes(x=x, y=y, label=Region), face="bold", size=8) +
  geom_text_repel(data=Locality, aes(x=x, y=y, label=Locality)) +
  scale_shape_manual(values=c(21,23,23,24,22)) + 
  scale_fill_viridis_d(option="C") +
  guides(fill = guide_legend(override.aes = list(pch = 22))) +
  theme_bw() +
  theme(legend.position = "none") +
  theme(panel.grid = element_blank()) +
  xlab(paste0("PC1 ",round(pvar[1]*100,2), "%" )) +
  ylab(paste0("PC2 ",round(pvar[2]*100,2), "%" )) +
  ggtitle("Genome-Wide PCA of Australasian Fish") +
  theme(plot.title = element_text(size=14, face="bold", hjust=0.5)) 

ggsave("outputs/1305/genome-wide-pcs12.pdf", width=8, height=6)
```


```{r}
x <- pcadapt(filename, K = 4)
summary(x)
```

```{r}
plot(x , option = "manhattan")
```

```{r}
plot(x, option = "qqplot")
```

```{r}
hist(x$pvalues, xlab = "p-values", main = NULL, breaks = 50, col = "orange")
```

```{r}
plot(x, option = "stat.distribution")
```


Manual suggests LD thining for snps from WGS data, but not RAD, checking for clustering around certain regions    
```{R}
par(mfrow = c(2, 2))
for (i in 1:4)
  plot(x$loadings[, i], pch = 19, cex = .3, ylab = paste0("Loadings PC", i))
```    
```{r}
plot(x)
```
```{r}
padj <- p.adjust(x$pvalues,method="BH")
alpha <- 0.05
outliers <- which(padj < alpha)
length(outliers)

snp_pc <- get.pc(x, outliers)
snp_pc %>% group_by(PC) %>% summarize(Count=n())

```

```{r}
padj <- p.adjust(x$pvalues,method = "BH")
alpha <- 0.05
outliers <- which(padj < alpha)
length(outliers)

snp_pc <- get.pc(x, outliers)
snp_pc %>% group_by(PC) %>% summarize(Count=n())

```

cat pruned-05.vcf | grep -v "^#" | cut -f1-3 | awk '{print $0"\t"NR}' > pruned-05-snp-numbers.tsv


```{r}
snp_pc %>% filter(PC==3)
```


```{r}
snpnumbers<-read_tsv("outputs/1309/pruned-05-snp-numbers.tsv", col_names = c("Chrom","Pos","Marker","SNP"))
snps<-left_join(as_tibble(snp_pc), snpnumbers) 

snps %>% group_by(PC, Chrom) %>% summarize(Count=n()) %>% arrange(-Count)
```


```{r}
snps %>% filter(PC==3)
```

```{r}
snps %>% filter(PC==1)
```


# Phylo

```{sh, eval=FALSE}
conda activate py2;
~/github/mccloud-rrt/vcf2phylip.py -i pruned-05.vcf;
~/github/mccloud-rrt/vcf2phylip.py -i pruned-05-rand.vcf;

conda deactivate;

iqtree2  -nt AUTO -m MFP+ASC -bb 1000 -s pruned-05.min4.phy --seqtype DNA --redo
iqtree2  -nt AUTO -m MFP+ASC -bb 10000 -s pruned-05.min4.phy.varsites.phy --seqtype DNA --redo


iqtree2  -nt AUTO -m MFP+ASC -bb 1000 -s pruned-05-rand.min4.phy --seqtype DNA --redo
iqtree2  -nt AUTO -m MFP+ASC -bb 10000 -s pruned-05-rand.min4.phy.varsites.phy --seqtype DNA --redo
```


```{r}
dat<-read.dna(file="outputs/1309/phylo/pruned-05.min4.phy.varsites.phy")
write.nexus.data(dat, file="outputs/1309/phylo/pruned-05-maf05.nex")

dat<-read.dna(file="outputs/1309/phylo/pruned-05-rand.min4.phy.varsites.phy")
write.nexus.data(dat, file="outputs/1309/phylo/pruned-05-rand.nex")
```



```{r}
net<-read.nexus.networx("outputs/1309/phylo/pruned-05-maf05-network")
m<-meta
```

```{r}
g<-ggsplitnet(net, color="black")  
g$data<-left_join(g$data, m, by=c("label"="Run")) 

n<-g + 
  geom_tippoint(aes(fill=Locality), cex=5, alpha=1.00, pch=21) +
  scale_fill_viridis_d(option="H") +
  guides(fill = guide_legend(override.aes = list(pch = 22))) +
#  theme(legend.position = "none") +
  theme(panel.grid=element_blank())
  #theme(panel.background = element_rect(fill="black", color="black")) +
  #theme(plot.background = element_rect(fill="black", color="black")) +
  #theme(legend.background =element_rect(fill="black", color="black"), legend.text = element_text(color="white"), legend.title = element_text(color="white")) +
  #theme(axis.text=element_text(color="white", size=12)) +
  #theme(axis.title=element_text(color="white", face="bold", size=14))  +
 # theme(legend.position = "none")
  
  
  #color white and black
n
ggsave("outputs/1309/aus-wgs-network.jpeg", width=10, height=8)
ggsave("outputs/1309/aus-wgs-network.pdf", width=10, height=8)

```


```{r}
net<-read.nexus.networx("outputs/1309/phylo/pruned-05-rand-network")
m<-meta
```

```{r}
g<-ggsplitnet(net, color="black")  
g$data<-left_join(g$data, m, by=c("label"="Run")) 

n<-g + 
  geom_tippoint(aes(fill=Locality), cex=5, alpha=1.00, pch=21) +
  scale_fill_viridis_d(option="H") +
  guides(fill = guide_legend(override.aes = list(pch = 22))) +
#  theme(legend.position = "none") +
  theme(panel.grid=element_blank())
  #theme(panel.background = element_rect(fill="black", color="black")) +
  #theme(plot.background = element_rect(fill="black", color="black")) +
  #theme(legend.background =element_rect(fill="black", color="black"), legend.text = element_text(color="white"), legend.title = element_text(color="white")) +
  #theme(axis.text=element_text(color="white", size=12)) +
  #theme(axis.title=element_text(color="white", face="bold", size=14))  +
 # theme(legend.position = "none")
  
  
  #color white and black
n

```

WAF011639

```{r}
tree<-read.tree("outputs/1309/phylo/pruned-05-rand.min4.phy.varsites.phy.contree")
t1<-ggtree(tree) + geom_nodelab(aes(label=node)) +geom_tiplab()
t1
```

```{r}
#ind<-m %>% filter(Lineage=="IND")
#t2<-root.phylo(tree,outgroup = ind$Run)
#t2<-midpoint.root(t2)
#t2<-root.phylo(tree, node=98)
t3<-as.polytomy(tree, feature='node.label', fun=function(x) as.numeric(x) < 25)
t3<-midpoint(tree)
t<-t3
t<-drop.tip(t,"WAF011639")
t<-drop.tip(t,"Broome01")
t<-ggtree(t)

t$data$Bootstrap<-as.numeric(t$data$label)

d <- t$data
d <- d[!d$isTip,]
d$label <- as.numeric(d$label)
d <- d[d$label >= 90,]

e <- t$data
e <- e[!e$isTip,]
e$label <- as.numeric(e$label)
e <- e[e$label < 90,]
e <- e[e$label >= 75,]


f <- t$data
f <- f[!f$isTip,]
f$label <- as.numeric(f$label)
f <- f[f$label < 75,]
f <- f[f$label >= 50,]
```

```{r}
u<-t %<+% dplyr::select(meta, -`...1`) + #bind_rows(m58, rm) +
  geom_point(data=d,  fill="black", cex=3, alpha=1, pch=22) +
  geom_point(data=e,  fill="gray50", cex=3, alpha=1, pch=22) +
  geom_point(data=f,  fill="grey90", cex=3, alpha=1, pch=22) +
  geom_tippoint(aes(x=x+0.002,fill=Locality, shape=Lineage), cex=4) + 
  geom_tiplab(aes(label=paste0(Locality, " ",label), x=x+0.01), align = FALSE, size=3) +
  #geom_text(data=t$data %>% filter(isTip==TRUE) %>% filter(label %in% Run), aes(label=label, x=x+0.01), size=3) +
  scale_shape_manual(values=c(21,23,24)) +
  guides(fill = guide_legend(override.aes = list(pch = 22))) +
  xlim(0,.2) +
  scale_fill_viridis_d(option="H") +
  theme(legend.position = "none") +
  geom_treescale(x = 0)

u

ggsave("outputs/1309/aus-phylo.pdf", width=6, height=9)
```