---
title: "1402-no-og"
output: html_document
date: "2026-03-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


```{r}
library(ape)
library(phangorn)
library(tidyverse)
library(pcadapt)
library(ggpubr)
library(grid)
library(ggrepel)
library(ggtree)
library(tanggle)
```

Calling SNPs not including L. japonicus

```{sh, eval=FALSE}
srun -t 48:00:00 -p bmh --mem=32G --nodes=1 --ntasks-per-node=1 --cpus-per-task=12 $HOME/angsd/angsd -nthreads 12 \
-minInd 125 -bam bamlists/139.bamlist -ref genome/GCF_001640805.2_TLL_Latcal_v3_genomic.fna \
-rf  meta/no-inv.txt -out outputs/1402/snps-wgs-01-glf  \
-minMaf 0.01 -minMapQ 20 -minQ 20 -GL 1 -doGLF 2 -doMajorMinor 1 -doMaf 1 -SNP_pval 1e-6 \
-doGeno 2 -doPost 1 -postCutoff 0.9 -doPlink 2  > outputs/1402/snps-wgs-01-glf.out 2> outputs/1402/snps-wgs-01-glf.err &
```


```{sh, eval=FALSE}
plink --tped snps-wgs-01-glf.tped --tfam snps-wgs-01-glf.tfam  --out plink-binary-01 --recode --allow-extra-chr --noweb
plink --ped plink-binary-01.ped --map plink-binary-01.map --recode vcf --allow-extra-chr -out plink-01
bgzip plink-01.vcf 
tabix plink-01.vcf.gz

#renaming vcf bcftools/1.13
module load bcftools

bcftools reheader --samples bamlists/139.names -o outputs/1402/renamed-01.vcf.gz outputs/1402/plink-01.vcf.gz
#bcftools view -S bamlists/89.names -o outputs/1402/renamed-01.vcf.gz outputs/1402/renamed-01-90.vcf.gz

bcftools +fill-tags outputs/1402/renamed-01.vcf.gz  -- -t MAF,F_MISSING | bcftools view -i 'F_MISSING < 0.05' | bcftools view -i 'INFO/MAF > 0.01' | bcftools view -i 'INFO/MAF < 0.45' |  bcftools +prune -m 0.20 -w 50kb --nsites-per-win 1 --nsites-per-win-mode rand  > outputs/1402/pruned-01-maf01-45.vcf

bcftools +fill-tags outputs/1402/renamed-01.vcf.gz  -- -t MAF,F_MISSING | bcftools view -i 'F_MISSING < 0.05' | bcftools view -i 'INFO/MAF > 0.05' | bcftools view -i 'INFO/MAF < 0.45' |  bcftools +prune -m 0.20 -w 50kb --nsites-per-win 1 --nsites-per-win-mode rand  > outputs/1402/pruned-01-maf05-45.vcf

bcftools +fill-tags outputs/1402/renamed-01.vcf.gz  -- -t MAF,F_MISSING | bcftools view -i 'F_MISSING < 0.05' | bcftools view -i 'INFO/MAF > 0.10' | bcftools view -i 'INFO/MAF < 0.45' |  bcftools +prune -m 0.20 -w 50kb --nsites-per-win 1 --nsites-per-win-mode rand  > outputs/1402/pruned-01-maf10-45.vcf

bcftools +fill-tags outputs/1402/renamed-01.vcf.gz  -- -t MAF,F_MISSING | bcftools view -i 'F_MISSING < 0.05' | bcftools view -i 'INFO/MAF > 0.10' | bcftools view -i 'INFO/MAF < 0.45' |  bcftools +prune -m 0.20 -w 50kb --nsites-per-win 1 --nsites-per-win-mode maxAF  > outputs/1402/pruned-01-maf10-45-max.vcf


#Convert to phylip and then to nex
conda activate py27;

~/mccloud-rrt/vcf2phylip.py -i pruned-01-maf01-45.vcf;
~/mccloud-rrt/vcf2phylip.py -i pruned-01-maf05-45.vcf;
~/mccloud-rrt/vcf2phylip.py -i pruned-01-maf10-45-max.vcf;
~/mccloud-rrt/vcf2phylip.py -i pruned-01-maf10-45.vcf;

conda deactivate
```

_4_ Network
```{r}
dat<-read.dna(file="outputs/1402/maf01/pruned-01-maf01-45.min4.phy")
write.nexus.data(dat, file="outputs/1402/maf01/pruned-01-maf01-45.min4.nex")


dat<-read.dna(file="outputs/1402/maf05/pruned-01-maf05-45.min4.phy")
write.nexus.data(dat, file="outputs/1402/maf05/pruned-01-maf05-45.min4.nex")

dat<-read.dna(file="outputs/1402/maf10-max/pruned-01-maf10-45-max.min4.phy")
write.nexus.data(dat, file="outputs/1402/maf10-max/pruned-01-maf10-45-max.min4.nex")

dat<-read.dna(file="outputs/1402/maf10-rand/pruned-01-maf10-45.min4.phy")
write.nexus.data(dat, file="outputs/1402/maf10-rand/pruned-01-maf10-45.min4.nex")
```
