---
title: "608.1-ld"
output: html_document
date: "2024-02-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


```{r}
library(tidyverse)
library(ggrepel)
library(pcadapt)
library(adegenet)
library(vcfR)
library(snpR)
library(ggpubr)
```


gunzip -c NC_066852.1.vcf.gz | grep "#" > header.txt
gunzip -c NC_066852.1.vcf.gz | grep -v "#" | awk 'BEGIN{i=0}{i++;if (i%100==0) print}' > NC_066852.1-thinned.vcf
gunzip -c NC_066852.1.vcf.gz | grep -v "#" | awk 'BEGIN{i=0}{i++;if (i%50==0) print}' > NC_066852.1-thinned.vcf

cat header.txt NC_066852.1-thinned.vcf > NC_066852.1-thinned.wheader.vcf

wc -l NC_066852.1-thinned.vcf 
1238 snps 
2380 with 50

plink --vcf NC_066852.1-thinned.wheader.vcf --r2 inter-chr --ld-window-r2 0.3 --out NC_066852.1-thinned.ldf --allow-extra-chr --double-id


```{r}
lc<-read.delim("outputs/608/vcf/NC_066852.1-thinned.ldf.ld",sep="",stringsAsFactors=FALSE) %>% as_tibble() %>% arrange(R2) %>%  filter(R2 >0.7)

  ggplot(lc) +
  geom_point(aes(x=BP_A, y=BP_B, color=R2), alpha=0.5) +
  scale_color_gradient(low="khaki1", high="red") + 
  theme_bw()
```


```{sh, eval=FALSE}
for f in *1.vcf.gz; do plink --vcf $f --r2 inter-chr gz --ld-window-r2 0.5 --out `basename $f vcf`ldf --allow-extra-chr --double-id; done;
```


```{r, eval=FALSE}
files<-list.files("outputs/608/vcf-pruned/",pattern = "*066852.1.vcf.gzldf.ld.gz", full.names = TRUE)

plotLd<-function(file) {
  chrom<-gsub("outputs/608/vcf-pruned/","",file)
  chrom<-gsub("1.vcf.gzldf.ld.gz","", chrom)
  lc<-read.delim(file,sep="",stringsAsFactors=FALSE) %>% as_tibble() %>% arrange(R2) %>%  filter(R2 >0.5)

  ggplot(lc) +
  geom_point(aes(x=BP_A, y=BP_B, color=R2), alpha=0.5) +
  scale_color_gradient(low="khaki1", high="red") + 
  theme_bw()
ggsave(paste0("outputs/608/ld/",chrom,".jpeg"))
}

lapply(files, plotLd)
```
