seqtk trimfq -e 50 data/lakdiva/Mannar1_R1.fastq.gz | gzip > data/lakdiva-trim/Mannar1_R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar2_R1.fastq.gz | gzip > data/lakdiva-trim/Mannar2_R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar3_R1.fastq.gz | gzip > data/lakdiva-trim/Mannar3_R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar4_R1.fastq.gz | gzip > data/lakdiva-trim/Mannar4_R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar5_R1.fastq.gz | gzip > data/lakdiva-trim/Mannar5_R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Trinco1_R1.fastq.gz | gzip > data/lakdiva-trim/Trinco1_R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Trinco2_R1.fastq.gz | gzip > data/lakdiva-trim/Trinco2_R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Trinco3_R1.fastq.gz | gzip > data/lakdiva-trim/Trinco3_R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Jaffna1_R1.fastq.gz | gzip > data/lakdiva-trim/Jaffna1_R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Jaffna2_R1.fastq.gz | gzip > data/lakdiva-trim/Jaffna2_R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar1_R2.fastq.gz | gzip > data/lakdiva-trim/Mannar1_R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar2_R2.fastq.gz | gzip > data/lakdiva-trim/Mannar2_R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar3_R2.fastq.gz | gzip > data/lakdiva-trim/Mannar3_R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar4_R2.fastq.gz | gzip > data/lakdiva-trim/Mannar4_R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar5_R2.fastq.gz | gzip > data/lakdiva-trim/Mannar5_R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Trinco1_R2.fastq.gz | gzip > data/lakdiva-trim/Trinco1_R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Trinco2_R2.fastq.gz | gzip > data/lakdiva-trim/Trinco2_R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Trinco3_R2.fastq.gz | gzip > data/lakdiva-trim/Trinco3_R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Jaffna1_R2.fastq.gz | gzip > data/lakdiva-trim/Jaffna1_R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Jaffna2_R2.fastq.gz | gzip > data/lakdiva-trim/Jaffna2_R2.fastq.gz
