seqtk trimfq -e 50 data/lakdiva/Mannar1-R1.fastq.gz | gzip > data/lakdiva-trim/Mannar1-R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar2-R1.fastq.gz | gzip > data/lakdiva-trim/Mannar2-R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar3-R1.fastq.gz | gzip > data/lakdiva-trim/Mannar3-R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar4-R1.fastq.gz | gzip > data/lakdiva-trim/Mannar4-R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar5-R1.fastq.gz | gzip > data/lakdiva-trim/Mannar5-R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Trinco1-R1.fastq.gz | gzip > data/lakdiva-trim/Trinco1-R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Trinco2-R1.fastq.gz | gzip > data/lakdiva-trim/Trinco2-R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Trinco3-R1.fastq.gz | gzip > data/lakdiva-trim/Trinco3-R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Jaffna1-R1.fastq.gz | gzip > data/lakdiva-trim/Jaffna1-R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Jaffna2-R1.fastq.gz | gzip > data/lakdiva-trim/Jaffna2-R1.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar1-R2.fastq.gz | gzip > data/lakdiva-trim/Mannar1-R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar2-R2.fastq.gz | gzip > data/lakdiva-trim/Mannar2-R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar3-R2.fastq.gz | gzip > data/lakdiva-trim/Mannar3-R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar4-R2.fastq.gz | gzip > data/lakdiva-trim/Mannar4-R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Mannar5-R2.fastq.gz | gzip > data/lakdiva-trim/Mannar5-R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Trinco1-R2.fastq.gz | gzip > data/lakdiva-trim/Trinco1-R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Trinco2-R2.fastq.gz | gzip > data/lakdiva-trim/Trinco2-R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Trinco3-R2.fastq.gz | gzip > data/lakdiva-trim/Trinco3-R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Jaffna1-R2.fastq.gz | gzip > data/lakdiva-trim/Jaffna1-R2.fastq.gz
seqtk trimfq -e 50 data/lakdiva/Jaffna2-R2.fastq.gz | gzip > data/lakdiva-trim/Jaffna2-R2.fastq.gz
