samtools view -bs NA data/hatch-trim/Mainstream1.sort.flt.bam > /home/maccamp/lates-wgs/data/downsample/Mainstream1.reduced.bam
samtools view -bs NA data/hatch-trim/Mainstream2.sort.flt.bam > /home/maccamp/lates-wgs/data/downsample/Mainstream2.reduced.bam
samtools view -bs NA data/hatch-trim/Mainstream3.sort.flt.bam > /home/maccamp/lates-wgs/data/downsample/Mainstream3.reduced.bam
samtools view -bs NA data/hatch-trim/Mainstream4.sort.flt.bam > /home/maccamp/lates-wgs/data/downsample/Mainstream4.reduced.bam
samtools view -bs NA data/hatch-trim/Mainstream5.sort.flt.bam > /home/maccamp/lates-wgs/data/downsample/Mainstream5.reduced.bam
samtools view -bs NA data/hatch-trim/OceanPick11.sort.flt.bam > /home/maccamp/lates-wgs/data/downsample/OceanPick11.reduced.bam
samtools view -bs NA data/hatch-trim/OceanPick15.sort.flt.bam > /home/maccamp/lates-wgs/data/downsample/OceanPick15.reduced.bam
samtools view -bs NA data/hatch-trim/OceanPick16.sort.flt.bam > /home/maccamp/lates-wgs/data/downsample/OceanPick16.reduced.bam
samtools view -bs NA data/hatch-trim/OceanPick17.sort.flt.bam > /home/maccamp/lates-wgs/data/downsample/OceanPick17.reduced.bam
samtools view -bs NA data/hatch-trim/OceanPick1.sort.flt.bam > /home/maccamp/lates-wgs/data/downsample/OceanPick1.reduced.bam
samtools view -bs NA data/hatch-trim/OceanPick20.sort.flt.bam > /home/maccamp/lates-wgs/data/downsample/OceanPick20.reduced.bam
samtools view -bs NA data/hatch-trim/OceanPick2.sort.flt.bam > /home/maccamp/lates-wgs/data/downsample/OceanPick2.reduced.bam
samtools view -bs NA data/hatch-trim/OceanPick3.sort.flt.bam > /home/maccamp/lates-wgs/data/downsample/OceanPick3.reduced.bam
samtools view -bs NA data/hatch-trim/OceanPick5.sort.flt.bam > /home/maccamp/lates-wgs/data/downsample/OceanPick5.reduced.bam
samtools view -bs NA data/hatch-trim/OceanPick8.sort.flt.bam > /home/maccamp/lates-wgs/data/downsample/OceanPick8.reduced.bam
