cat data/hatcheries/Mainstream-1_*R1.fastq.gz > data/hatcheries/Mainstream1_R1.fastq.gz
cat data/hatcheries/Mainstream-2_*R1.fastq.gz > data/hatcheries/Mainstream2_R1.fastq.gz
cat data/hatcheries/Mainstream-3_*R1.fastq.gz > data/hatcheries/Mainstream3_R1.fastq.gz
cat data/hatcheries/Mainstream-4_*R1.fastq.gz > data/hatcheries/Mainstream4_R1.fastq.gz
cat data/hatcheries/Mainstream-5_*R1.fastq.gz > data/hatcheries/Mainstream5_R1.fastq.gz
cat data/hatcheries/OceanPick-11_*R1.fastq.gz > data/hatcheries/OceanPick11_R1.fastq.gz
cat data/hatcheries/OceanPick-15_*R1.fastq.gz > data/hatcheries/OceanPick15_R1.fastq.gz
cat data/hatcheries/OceanPick-16_*R1.fastq.gz > data/hatcheries/OceanPick16_R1.fastq.gz
cat data/hatcheries/OceanPick-17_*R1.fastq.gz > data/hatcheries/OceanPick17_R1.fastq.gz
cat data/hatcheries/OceanPick-1_*R1.fastq.gz > data/hatcheries/OceanPick1_R1.fastq.gz
cat data/hatcheries/OceanPick-20_*R1.fastq.gz > data/hatcheries/OceanPick20_R1.fastq.gz
cat data/hatcheries/OceanPick-2_*R1.fastq.gz > data/hatcheries/OceanPick2_R1.fastq.gz
cat data/hatcheries/OceanPick-3_*R1.fastq.gz > data/hatcheries/OceanPick3_R1.fastq.gz
cat data/hatcheries/OceanPick-5_*R1.fastq.gz > data/hatcheries/OceanPick5_R1.fastq.gz
cat data/hatcheries/OceanPick-8_*R1.fastq.gz > data/hatcheries/OceanPick8_R1.fastq.gz
