seqtk trimfq -e 50 data/hatcheries/Mainstream-1-R1.fastq.gz | gzip > data/hatch-trim/Mainstream-1-R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream-2-R1.fastq.gz | gzip > data/hatch-trim/Mainstream-2-R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream-3-R1.fastq.gz | gzip > data/hatch-trim/Mainstream-3-R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream-4-R1.fastq.gz | gzip > data/hatch-trim/Mainstream-4-R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream-5-R1.fastq.gz | gzip > data/hatch-trim/Mainstream-5-R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-11-R1.fastq.gz | gzip > data/hatch-trim/OceanPick-11-R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-15-R1.fastq.gz | gzip > data/hatch-trim/OceanPick-15-R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-16-R1.fastq.gz | gzip > data/hatch-trim/OceanPick-16-R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-17-R1.fastq.gz | gzip > data/hatch-trim/OceanPick-17-R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-1-R1.fastq.gz | gzip > data/hatch-trim/OceanPick-1-R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-20-R1.fastq.gz | gzip > data/hatch-trim/OceanPick-20-R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-2-R1.fastq.gz | gzip > data/hatch-trim/OceanPick-2-R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-3-R1.fastq.gz | gzip > data/hatch-trim/OceanPick-3-R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-5-R1.fastq.gz | gzip > data/hatch-trim/OceanPick-5-R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-8-R1.fastq.gz | gzip > data/hatch-trim/OceanPick-8-R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream-1-R2.fastq.gz | gzip > data/hatch-trim/Mainstream-1-R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream-2-R2.fastq.gz | gzip > data/hatch-trim/Mainstream-2-R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream-3-R2.fastq.gz | gzip > data/hatch-trim/Mainstream-3-R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream-4-R2.fastq.gz | gzip > data/hatch-trim/Mainstream-4-R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream-5-R2.fastq.gz | gzip > data/hatch-trim/Mainstream-5-R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-11-R2.fastq.gz | gzip > data/hatch-trim/OceanPick-11-R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-15-R2.fastq.gz | gzip > data/hatch-trim/OceanPick-15-R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-16-R2.fastq.gz | gzip > data/hatch-trim/OceanPick-16-R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-17-R2.fastq.gz | gzip > data/hatch-trim/OceanPick-17-R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-1-R2.fastq.gz | gzip > data/hatch-trim/OceanPick-1-R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-20-R2.fastq.gz | gzip > data/hatch-trim/OceanPick-20-R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-2-R2.fastq.gz | gzip > data/hatch-trim/OceanPick-2-R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-3-R2.fastq.gz | gzip > data/hatch-trim/OceanPick-3-R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-5-R2.fastq.gz | gzip > data/hatch-trim/OceanPick-5-R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-8-R2.fastq.gz | gzip > data/hatch-trim/OceanPick-8-R2.fastq.gz
