seqtk trimfq -e 50 data/hatcheries/Mainstream-1_R1.fastq.gz | gzip > data/hatch-trim/Mainstream-1_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream-2_R1.fastq.gz | gzip > data/hatch-trim/Mainstream-2_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream-3_R1.fastq.gz | gzip > data/hatch-trim/Mainstream-3_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream-4_R1.fastq.gz | gzip > data/hatch-trim/Mainstream-4_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream-5_R1.fastq.gz | gzip > data/hatch-trim/Mainstream-5_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-11_R1.fastq.gz | gzip > data/hatch-trim/OceanPick-11_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-15_R1.fastq.gz | gzip > data/hatch-trim/OceanPick-15_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-16_R1.fastq.gz | gzip > data/hatch-trim/OceanPick-16_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-17_R1.fastq.gz | gzip > data/hatch-trim/OceanPick-17_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-1_R1.fastq.gz | gzip > data/hatch-trim/OceanPick-1_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-20_R1.fastq.gz | gzip > data/hatch-trim/OceanPick-20_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-2_R1.fastq.gz | gzip > data/hatch-trim/OceanPick-2_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-3_R1.fastq.gz | gzip > data/hatch-trim/OceanPick-3_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-5_R1.fastq.gz | gzip > data/hatch-trim/OceanPick-5_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick-8_R1.fastq.gz | gzip > data/hatch-trim/OceanPick-8_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream1_R2.fastq.gz | gzip > data/lakdiva-trim/Mainstream1_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream2_R2.fastq.gz | gzip > data/lakdiva-trim/Mainstream2_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream3_R2.fastq.gz | gzip > data/lakdiva-trim/Mainstream3_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream4_R2.fastq.gz | gzip > data/lakdiva-trim/Mainstream4_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream5_R2.fastq.gz | gzip > data/lakdiva-trim/Mainstream5_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick11_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick11_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick15_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick15_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick16_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick16_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick17_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick17_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick1_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick1_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick20_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick20_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick2_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick2_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick3_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick3_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick5_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick5_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick8_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick8_R2.fastq.gz
