cat data/hatcheries/Mainstream-1_*R2.fastq.gz > data/hatcheries/Mainstream1_R2.fastq.gz
cat data/hatcheries/Mainstream-2_*R2.fastq.gz > data/hatcheries/Mainstream2_R2.fastq.gz
cat data/hatcheries/Mainstream-3_*R2.fastq.gz > data/hatcheries/Mainstream3_R2.fastq.gz
cat data/hatcheries/Mainstream-4_*R2.fastq.gz > data/hatcheries/Mainstream4_R2.fastq.gz
cat data/hatcheries/Mainstream-5_*R2.fastq.gz > data/hatcheries/Mainstream5_R2.fastq.gz
cat data/hatcheries/OceanPick-11_*R2.fastq.gz > data/hatcheries/OceanPick11_R2.fastq.gz
cat data/hatcheries/OceanPick-15_*R2.fastq.gz > data/hatcheries/OceanPick15_R2.fastq.gz
cat data/hatcheries/OceanPick-16_*R2.fastq.gz > data/hatcheries/OceanPick16_R2.fastq.gz
cat data/hatcheries/OceanPick-17_*R2.fastq.gz > data/hatcheries/OceanPick17_R2.fastq.gz
cat data/hatcheries/OceanPick-1_*R2.fastq.gz > data/hatcheries/OceanPick1_R2.fastq.gz
cat data/hatcheries/OceanPick-20_*R2.fastq.gz > data/hatcheries/OceanPick20_R2.fastq.gz
cat data/hatcheries/OceanPick-2_*R2.fastq.gz > data/hatcheries/OceanPick2_R2.fastq.gz
cat data/hatcheries/OceanPick-3_*R2.fastq.gz > data/hatcheries/OceanPick3_R2.fastq.gz
cat data/hatcheries/OceanPick-5_*R2.fastq.gz > data/hatcheries/OceanPick5_R2.fastq.gz
cat data/hatcheries/OceanPick-8_*R2.fastq.gz > data/hatcheries/OceanPick8_R2.fastq.gz
