seqtk trimfq -e 50 data/hatcheries/Mainstream1_R1.fastq.gz | gzip > data/hatch-trim/Mainstream1_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream2_R1.fastq.gz | gzip > data/hatch-trim/Mainstream2_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream3_R1.fastq.gz | gzip > data/hatch-trim/Mainstream3_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream4_R1.fastq.gz | gzip > data/hatch-trim/Mainstream4_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream5_R1.fastq.gz | gzip > data/hatch-trim/Mainstream5_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick11_R1.fastq.gz | gzip > data/hatch-trim/OceanPick11_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick15_R1.fastq.gz | gzip > data/hatch-trim/OceanPick15_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick16_R1.fastq.gz | gzip > data/hatch-trim/OceanPick16_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick17_R1.fastq.gz | gzip > data/hatch-trim/OceanPick17_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick1_R1.fastq.gz | gzip > data/hatch-trim/OceanPick1_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick20_R1.fastq.gz | gzip > data/hatch-trim/OceanPick20_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick2_R1.fastq.gz | gzip > data/hatch-trim/OceanPick2_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick3_R1.fastq.gz | gzip > data/hatch-trim/OceanPick3_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick5_R1.fastq.gz | gzip > data/hatch-trim/OceanPick5_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick8_R1.fastq.gz | gzip > data/hatch-trim/OceanPick8_R1.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream1_R2.fastq.gz | gzip > data/lakdiva-trim/Mainstream1_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream2_R2.fastq.gz | gzip > data/lakdiva-trim/Mainstream2_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream3_R2.fastq.gz | gzip > data/lakdiva-trim/Mainstream3_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream4_R2.fastq.gz | gzip > data/lakdiva-trim/Mainstream4_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/Mainstream5_R2.fastq.gz | gzip > data/lakdiva-trim/Mainstream5_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick11_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick11_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick15_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick15_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick16_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick16_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick17_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick17_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick1_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick1_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick20_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick20_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick2_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick2_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick3_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick3_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick5_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick5_R2.fastq.gz
seqtk trimfq -e 50 data/hatcheries/OceanPick8_R2.fastq.gz | gzip > data/lakdiva-trim/OceanPick8_R2.fastq.gz
