---
title: "902-copy-number-variation"
output: html_document
date: "2024-08-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
```

Should be easily able to calculate depth (samtools depth -a ) and create a depth raster.

Queensland
India (east coast and west)
Indonesia (K, SU, SJ)

Need to normalize. Divide by average depth?

1 2 3 = 6, 1/2, 1, 3/2 = 3
1 1 1 = 1, 1 + 1 +1 = 3


```{r}
msub<-read_csv("~/github/lates-wgs/meta/58-Indo-split.csv") %>% 
  filter(Region %in% c("Queensland","India Eastern Coast","India Western Coast","Indonesia-K",
                       "Indonesia-SJ","Indonesia-SU"))
```

```{r}
commands<-msub %>% mutate(Command=paste0("samtools view -bh -r NC_066833.1,NC_066834.1 ", Path, " | samtools depth -a - | awk '{print $1, $2, $3/",Coverage,"\t",Run,"}' ", ">", " outputs/902/",Run,".coverage"))

commands %>% select(Command) %>% write_tsv("902-coverage.sh", col_names = FALSE)
```

module load parallel
 
srun -p high --time 2:00:00 --nodes=1 --ntasks-per-node=1 --cpus-per-task=18 parallel -j 18 < 902-coverage.sh

Combine into a tidy format.

Chrom Pos Depth Individual
~ X Z Y
